
dependencies {
    compileOnly project(":eventuate-tram-events")
    implementation project(":eventuate-tram-messaging")
    implementation "io.eventuate.common:eventuate-common-json-mapper:$eventuateCommonVersion"
    
    compileOnly "org.springframework.boot:spring-boot-starter:$springBootVersion"
    compileOnly "org.springframework.boot:spring-boot-starter-jdbc:$springBootVersion"

    implementation "com.jayway.jsonpath:json-path:$jsonPathVersion"

    implementation "org.hamcrest:hamcrest:$hamcrestVersion"
    implementation "org.junit.jupiter:junit-jupiter-api:$junitVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}