
dependencies {
    api project (":eventuate-tram-consumer-common")
    api project(":eventuate-tram-optimistic-locking-common-test")
    api "org.springframework.boot:spring-boot-starter-jdbc:$springBootVersion"
    api "io.eventuate.common:eventuate-common-spring-jdbc:$eventuateCommonVersion"
    api "org.springframework.boot:spring-boot-starter-data-jpa:$springBootVersion"

    testImplementation "org.springframework.boot:spring-boot-starter-data-jpa-test:$springBootVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
