CREATE SCHEMA IF NOT EXISTS eventuate AUTHORIZATION SA;

drop table if exists eventuate.message;

CREATE TABLE eventuate.message (
  ID VARCHAR(1000) PRIMARY KEY,
  DESTINATION VARCHAR(1000) NOT NULL,
  HEADERS VARCHAR(1000) NOT NULL,
  PAYLOAD VARCHAR(1000) NOT NULL,
  MESSAGE_PARTITION SMALLINT,
  CREATION_TIME BIGINT
);

drop table if exists eventuate.received_messages;

CREATE TABLE eventuate.received_messages (
  CONSUMER_ID VARCHAR(1000),
  MESSAGE_ID VARCHAR(1000),
  CREATION_TIME BIGINT,
  PRIMARY KEY(CONSUMER_ID, MESSAGE_ID)
);
