if [ -z "$DOCKER_HOST_IP" ] ; then
    if [ -z "$DOCKER_HOST" ] ; then
      export DOCKER_HOST_IP=`hostname`
    else
      echo using ${DOCKER_HOST?}
      XX=${DOCKER_HOST%\:*}
      export DOCKER_HOST_IP=${XX#tcp\:\/\/}
    fi
fi

echo DOCKER_HOST_IP is $DOCKER_HOST_IP

export EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS=$DOCKER_HOST_IP:9092
export EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING=$DOCKER_HOST_IP:2181
export ACTIVEMQ_URL=tcp://${DOCKER_HOST_IP}:61616
export RABBITMQ_URL=${DOCKER_HOST_IP}
export REDIS_HOST=${DOCKER_HOST_IP}
export REDIS_PORT=6379
export EVENTUATE_EVENT_TRACKER_ITERATIONS=120
export EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID=1234567890
export REDIS_PARTITIONS=2
export REDIS_ADDITIONAL_SERVERS=redis://${DOCKER_HOST_IP}:6380,redis://${DOCKER_HOST_IP}:6381
