. ./_set-env.sh

export SPRING_DATASOURCE_URL=jdbc:mysql://${DOCKER_HOST_IP}/eventuate
export SPRING_DATASOURCE_USERNAME=mysqluser
export SPRING_DATASOURCE_PASSWORD=mysqlpw
export SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver

export DATASOURCE_URL=jdbc:mysql://${DOCKER_HOST_IP}/eventuate
export DATASOURCE_USERNAME=mysqluser
export DATASOURCE_PASSWORD=mysqlpw
export DATASOURCE_DRIVERCLASSNAME=com.mysql.jdbc.Driver

export EVENTUATE_REDIS_SERVERS=${DOCKER_HOST_IP}:6379
export EVENTUATE_REDIS_PARTITIONS=1

export SPRING_PROFILES_ACTIVE=Redis

