. ./_set-env.sh

export SPRING_DATASOURCE_URL=jdbc:mysql://${DOCKER_HOST_IP}/eventuate
export SPRING_DATASOURCE_USERNAME=mysqluser
export SPRING_DATASOURCE_PASSWORD=mysqlpw
export SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
export EVENTUATELOCAL_CDC_DB_USER_NAME=root
export EVENTUATELOCAL_CDC_DB_PASSWORD=rootpassword
export EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC=false
export EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID=1234567890
export EVENTUATELOCAL_CDC_READER_NAME=MySqlReader
export EVENTUATELOCAL_CDC_OFFSET_STORE_KEY=MySqlBinlog
export ACTIVEMQ_URL=tcp://${DOCKER_HOST_IP}:61616
export RABBITMQ_URL=${DOCKER_HOST_IP}
export REDIS_SERVERS=${DOCKER_HOST_IP}:6379
export REDIS_PARTITIONS=2

unset SPRING_PROFILES_ACTIVE
