
dependencies {
    api project(":eventuate-tram-test-util")

    compileOnly "org.springframework.boot:spring-boot-starter:$springBootVersion"

    testImplementation project(":eventuate-tram-spring-in-memory")
    testImplementation "org.springframework.boot:spring-boot-starter-jdbc-test:$springBootVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
