
dependencies {
    api "org.springframework.boot:spring-boot-starter:$springBootVersion"

    api project(":eventuate-tram-consumer-jdbc")

    api "io.eventuate.common:eventuate-common-spring-jdbc:$eventuateCommonVersion"

    testImplementation "org.springframework.boot:spring-boot-starter-jdbc-test:$springBootVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
