
dependencies {
    api project(":eventuate-tram-messaging")
    api project(":eventuate-tram-consumer-common")
    api project(":eventuate-tram-messaging-producer-common")

    api project(":eventuate-tram-consumer-jdbc")

    api "io.eventuate.common:eventuate-common-id:$eventuateCommonVersion"
    api "com.h2database:h2:$h2Version"
    api "io.eventuate.common:eventuate-common-in-memory-database:$eventuateCommonVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
